// https://www.postgresql.org/docs/current/errcodes-appendix.html
const errorCode = [
  { code: '00000', description: 'successful completion' },
  { code: '01000', description: 'warning' },
  { code: '0100C', description: 'dynamic result sets returned' },
  { code: '01008', description: 'implicit zero bit padding' },
  { code: '01003', description: 'null value eliminated in set function' },
  { code: '01007', description: 'privilege not granted' },
  { code: '01006', description: 'privilege not revoked' },
  { code: '01004', description: 'string data right truncation' },
  { code: '01P01', description: 'deprecated feature' },
  { code: '02000', description: 'no data' },
  { code: '02001', description: 'no additional dynamic result sets returned' },
  { code: '03000', description: 'sql statement not yet complete' },
  { code: '08000', description: 'connection exception' },
  { code: '08003', description: 'connection does not exist' },
  { code: '08006', description: 'connection failure' },
  { code: '08001', description: 'sqlclient unable to establish sqlconnection' },
  { code: '08004', description: 'sqlserver rejected establishment of sqlconnection' },
  { code: '08007', description: 'transaction resolution unknown' },
  { code: '08P01', description: 'protocol violation' },
  { code: '09000', description: 'triggered action exception' },
  { code: '0A000', description: 'feature not supported' },
  { code: '0B000', description: 'invalid transaction initiation' },
  { code: '0F000', description: 'locator exception' },
  { code: '0F001', description: 'invalid locator specification' },
  { code: '0L000', description: 'invalid grantor' },
  { code: '0LP01', description: 'invalid grant operation' },
  { code: '0P000', description: 'invalid role specification' },
  { code: '0Z000', description: 'diagnostics exception' },
  { code: '0Z002', description: 'stacked diagnostics accessed without active handler' },
  { code: '20000', description: 'case not found' },
  { code: '21000', description: 'cardinality violation' },
  { code: '22000', description: 'data exception' },
  { code: '2202E', description: 'array subscript error' },
  { code: '22021', description: 'character not in repertoire' },
  { code: '22008', description: 'datetime field overflow' },
  { code: '22012', description: 'division by zero' },
  { code: '22005', description: 'error in assignment' },
  { code: '2200B', description: 'escape character conflict' },
  { code: '22022', description: 'indicator overflow' },
  { code: '22015', description: 'interval field overflow' },
  { code: '2201E', description: 'invalid argument for logarithm' },
  { code: '22014', description: 'invalid argument for ntile function' },
  { code: '22016', description: 'invalid argument for nth value function' },
  { code: '2201F', description: 'invalid argument for power function' },
  { code: '2201G', description: 'invalid argument for width bucket function' },
  { code: '22018', description: 'invalid character value for cast' },
  { code: '22007', description: 'invalid datetime format' },
  { code: '22019', description: 'invalid escape character' },
  { code: '2200D', description: 'invalid escape octet' },
  { code: '22025', description: 'invalid escape sequence' },
  { code: '22P06', description: 'nonstandard use of escape character' },
  { code: '22010', description: 'invalid indicator parameter value' },
  { code: '22023', description: 'invalid parameter value' },
  { code: '22013', description: 'invalid preceding or following size' },
  { code: '2201B', description: 'invalid regular expression' },
  { code: '2201W', description: 'invalid row count in limit clause' },
  { code: '2201X', description: 'invalid row count in result offset clause' },
  { code: '2202H', description: 'invalid tablesample argument' },
  { code: '2202G', description: 'invalid tablesample repeat' },
  { code: '22009', description: 'invalid time zone displacement value' },
  { code: '2200C', description: 'invalid use of escape character' },
  { code: '2200G', description: 'most specific type mismatch' },
  { code: '22004', description: 'null value not allowed' },
  { code: '22002', description: 'null value no indicator parameter' },
  { code: '22003', description: 'numeric value out of range' },
  { code: '2200H', description: 'sequence generator limit exceeded' },
  { code: '22026', description: 'string data length mismatch' },
  { code: '22001', description: 'string data right truncation' },
  { code: '22011', description: 'substring error' },
  { code: '22027', description: 'trim error' },
  { code: '22024', description: 'unterminated c string' },
  { code: '2200F', description: 'zero length character string' },
  { code: '22P01', description: 'floating point exception' },
  { code: '22P02', description: 'invalid text representation' },
  { code: '22P03', description: 'invalid binary representation' },
  { code: '22P04', description: 'bad copy file format' },
  { code: '22P05', description: 'untranslatable character' },
  { code: '2200L', description: 'not an xml document' },
  { code: '2200M', description: 'invalid xml document' },
  { code: '2200N', description: 'invalid xml content' },
  { code: '2200S', description: 'invalid xml comment' },
  { code: '2200T', description: 'invalid xml processing instruction' },
  { code: '22030', description: 'duplicate json object key value' },
  { code: '22032', description: 'invalid json text' },
  { code: '22033', description: 'invalid sql json subscript' },
  { code: '22034', description: 'more than one sql json item' },
  { code: '22035', description: 'no sql json item' },
  { code: '22036', description: 'non numeric sql json item' },
  { code: '22037', description: 'non unique keys in a json object' },
  { code: '22038', description: 'singleton sql json item required' },
  { code: '22039', description: 'sql json array not found' },
  { code: '2203A', description: 'sql json member not found' },
  { code: '2203B', description: 'sql json number not found' },
  { code: '2203C', description: 'sql json object not found' },
  { code: '2203D', description: 'too many json array elements' },
  { code: '2203E', description: 'too many json object members' },
  { code: '2203F', description: 'sql json scalar required' },
  { code: '23000', description: 'integrity constraint violation' },
  { code: '23001', description: 'restrict violation' },
  { code: '23502', description: 'not null violation' },
  { code: '23503', description: 'foreign key violation' },
  { code: '23505', description: 'unique violation' },
  { code: '23514', description: 'check violation' },
  { code: '23P01', description: 'exclusion violation' },
  { code: '24000', description: 'invalid cursor state' },
  { code: '25000', description: 'invalid transaction state' },
  { code: '25001', description: 'active sql transaction' },
  { code: '25002', description: 'branch transaction already active' },
  { code: '25008', description: 'held cursor requires same isolation level' },
  { code: '25003', description: 'inappropriate access mode for branch transaction' },
  { code: '25004', description: 'inappropriate isolation level for branch transaction' },
  { code: '25005', description: 'no active sql transaction for branch transaction' },
  { code: '25006', description: 'read only sql transaction' },
  { code: '25007', description: 'schema and data statement mixing not supported' },
  { code: '25P01', description: 'no active sql transaction' },
  { code: '25P02', description: 'in failed sql transaction' },
  { code: '25P03', description: 'idle in transaction session timeout' },
  { code: '26000', description: 'invalid sql statement name' },
  { code: '27000', description: 'triggered data change violation' },
  { code: '28000', description: 'invalid authorization specification' },
  { code: '28P01', description: 'invalid password' },
  { code: '2B000', description: 'dependent privilege descriptors still exist' },
  { code: '2BP01', description: 'dependent objects still exist' },
  { code: '2D000', description: 'invalid transaction termination' },
  { code: '2F000', description: 'sql routine exception' },
  { code: '2F005', description: 'function executed no return statement' },
  { code: '2F002', description: 'modifying sql data not permitted' },
  { code: '2F003', description: 'prohibited sql statement attempted' },
  { code: '2F004', description: 'reading sql data not permitted' },
  { code: '34000', description: 'invalid cursor name' },
  { code: '38000', description: 'external routine exception' },
  { code: '38001', description: 'containing sql not permitted' },
  { code: '38002', description: 'modifying sql data not permitted' },
  { code: '38003', description: 'prohibited sql statement attempted' },
  { code: '38004', description: 'reading sql data not permitted' },
  { code: '39000', description: 'external routine invocation exception' },
  { code: '39001', description: 'invalid sqlstate returned' },
  { code: '39004', description: 'null value not allowed' },
  { code: '39P01', description: 'trigger protocol violated' },
  { code: '39P02', description: 'srf protocol violated' },
  { code: '39P03', description: 'event trigger protocol violated' },
  { code: '3B000', description: 'savepoint exception' },
  { code: '3B001', description: 'invalid savepoint specification' },
  { code: '3D000', description: 'invalid catalog name' },
  { code: '3F000', description: 'invalid schema name' },
  { code: '40000', description: 'transaction rollback' },
  { code: '40002', description: 'transaction integrity constraint violation' },
  { code: '40001', description: 'serialization failure' },
  { code: '40003', description: 'statement completion unknown' },
  { code: '40P01', description: 'deadlock detected' },
  { code: '42000', description: 'syntax error or access rule violation' },
  { code: '42601', description: 'syntax error' },
  { code: '42501', description: 'insufficient privilege' },
  { code: '42846', description: 'cannot coerce' },
  { code: '42803', description: 'grouping error' },
  { code: '42P20', description: 'windowing error' },
  { code: '42P19', description: 'invalid recursion' },
  { code: '42830', description: 'invalid foreign key' },
  { code: '42602', description: 'invalid name' },
  { code: '42622', description: 'name too long' },
  { code: '42939', description: 'reserved name' },
  { code: '42804', description: 'datatype mismatch' },
  { code: '42P18', description: 'indeterminate datatype' },
  { code: '42P21', description: 'collation mismatch' },
  { code: '42P22', description: 'indeterminate collation' },
  { code: '42809', description: 'wrong object type' },
  { code: '428C9', description: 'generated always' },
  { code: '42703', description: 'undefined column' },
  { code: '42883', description: 'undefined function' },
  { code: '42P01', description: 'undefined table' },
  { code: '42P02', description: 'undefined parameter' },
  { code: '42704', description: 'undefined object' },
  { code: '42701', description: 'duplicate column' },
  { code: '42P03', description: 'duplicate cursor' },
  { code: '42P04', description: 'duplicate database' },
  { code: '42723', description: 'duplicate function' },
  { code: '42P05', description: 'duplicate prepared statement' },
  { code: '42P06', description: 'duplicate schema' },
  { code: '42P07', description: 'duplicate table' },
  { code: '42712', description: 'duplicate alias' },
  { code: '42710', description: 'duplicate object' },
  { code: '42702', description: 'ambiguous column' },
  { code: '42725', description: 'ambiguous function' },
  { code: '42P08', description: 'ambiguous parameter' },
  { code: '42P09', description: 'ambiguous alias' },
  { code: '42P10', description: 'invalid column reference' },
  { code: '42611', description: 'invalid column definition' },
  { code: '42P11', description: 'invalid cursor definition' },
  { code: '42P12', description: 'invalid database definition' },
  { code: '42P13', description: 'invalid function definition' },
  { code: '42P14', description: 'invalid prepared statement definition' },
  { code: '42P15', description: 'invalid schema definition' },
  { code: '42P16', description: 'invalid table definition' },
  { code: '42P17', description: 'invalid object definition' },
  { code: '44000', description: 'with check option violation' },
  { code: '53000', description: 'insufficient resources' },
  { code: '53100', description: 'disk full' },
  { code: '53200', description: 'out of memory' },
  { code: '53300', description: 'too many connections' },
  { code: '53400', description: 'configuration limit exceeded' },
  { code: '54000', description: 'program limit exceeded' },
  { code: '54001', description: 'statement too complex' },
  { code: '54011', description: 'too many columns' },
  { code: '54023', description: 'too many arguments' },
  { code: '55000', description: 'object not in prerequisite state' },
  { code: '55006', description: 'object in use' },
  { code: '55P02', description: 'cant change runtime param' },
  { code: '55P03', description: 'lock not available' },
  { code: '55P04', description: 'unsafe new enum value usage' },
  { code: '57000', description: 'operator intervention' },
  { code: '57014', description: 'query canceled' },
  { code: '57P01', description: 'admin shutdown' },
  { code: '57P02', description: 'crash shutdown' },
  { code: '57P03', description: 'cannot connect now' },
  { code: '57P04', description: 'database dropped' },
  { code: '58000', description: 'system error' },
  { code: '58030', description: 'io error' },
  { code: '58P01', description: 'undefined file' },
  { code: '58P02', description: 'duplicate file' },
  { code: '72000', description: 'snapshot too old' },
  { code: 'F0000', description: 'config file error' },
  { code: 'F0001', description: 'lock file exists' },
  { code: 'HV000', description: 'fdw error' },
  { code: 'HV005', description: 'fdw column name not found' },
  { code: 'HV002', description: 'fdw dynamic parameter value needed' },
  { code: 'HV010', description: 'fdw function sequence error' },
  { code: 'HV021', description: 'fdw inconsistent descriptor information' },
  { code: 'HV024', description: 'fdw invalid attribute value' },
  { code: 'HV007', description: 'fdw invalid column name' },
  { code: 'HV008', description: 'fdw invalid column number' },
  { code: 'HV004', description: 'fdw invalid data type' },
  { code: 'HV006', description: 'fdw invalid data type descriptors' },
  { code: 'HV091', description: 'fdw invalid descriptor field identifier' },
  { code: 'HV00B', description: 'fdw invalid handle' },
  { code: 'HV00C', description: 'fdw invalid option index' },
  { code: 'HV00D', description: 'fdw invalid option name' },
  { code: 'HV090', description: 'fdw invalid string length or buffer length' },
  { code: 'HV00A', description: 'fdw invalid string format' },
  { code: 'HV009', description: 'fdw invalid use of null pointer' },
  { code: 'HV014', description: 'fdw too many handles' },
  { code: 'HV001', description: 'fdw out of memory' },
  { code: 'HV00P', description: 'fdw no schemas' },
  { code: 'HV00J', description: 'fdw option name not found' },
  { code: 'HV00K', description: 'fdw reply handle' },
  { code: 'HV00Q', description: 'fdw schema not found' },
  { code: 'HV00R', description: 'fdw table not found' },
  { code: 'HV00L', description: 'fdw unable to create execution' },
  { code: 'HV00M', description: 'fdw unable to create reply' },
  { code: 'HV00N', description: 'fdw unable to establish connection' },
  { code: 'P0000', description: 'plpgsql error' },
  { code: 'P0001', description: 'raise exception' },
  { code: 'P0002', description: 'no data found' },
  { code: 'P0003', description: 'too many rows' },
  { code: 'P0004', description: 'assert failure' },
  { code: 'XX000', description: 'internal error' },
  { code: 'XX001', description: 'data corrupted' },
  { code: 'XX002', description: 'index corrupted' }
]

function searchCodeErrorPg(errorData) {
  // console.log(errorData);
  const send = errorCode.find((arr) => arr.code === errorData.code)

  if (send === undefined) {
    const description = `${errorData}`
    return {
      code: errorData.code,
      description
    }
  }

  const details = errorData.message

  return {
    code: errorData.code,
    description: send.description,
    details
  }
}

export default searchCodeErrorPg
